import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import '../public/css/animate.min.css';
import '../public/css/jquery-ui.css';
import '../public/css/responsive.css';
import '../public/css/normalize.css';
import Footer from "../app/footer/page";
import { WalletProviderContext } from "./WalletProviderContext/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WalletProviderContext>
        {children}
        </WalletProviderContext>
        <Footer />

        <script src="../public/js/bootstrap.bundle.min.js"></script>
        <script src="../public/js/custom.js"></script>
        <script src="../public/js/jquery-3.0.0.min.js"></script>
        <script src="../public/js/jquery.mCustomScrollbar.concat.min.js"></script>
        <script src="../public/js/jquery.min.js"></script>
        <script src="../public/js/jquery.validate.js"></script>
        <script src="../public/js/popper.min.js"></script>
        <script src="../public/js/plugin.js"></script>
      
  

    <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8eaHt9Dh5H57Zh0xVTqxVdBFCvFMqFjQ&callback=initMap"></script>
      </body>
    </html>
  );
}
