import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import '../public/css/animate.min.css';
// import '../public/css/jquery-ui.css';
// import '../public/css/responsive.css';
// import '../public/css/normalize.css';
import { WalletProviderContext } from "@/components/WalletProviderContext/page";
import Footer from "@/components/footer/page";
import Navbar from "@/components/navbar/page";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <WalletProviderContext>
          <>
            <Navbar />
            {children}
            <Footer />
          </>
        </WalletProviderContext>

      </body>
    </html>
  );
}
